COMMON:
  CKPT: checkpoints/checkpoint
  NUM_ANCHORS: 16
  INCREASE_BASE: 1.28
  MIN_ANCHOR_HEIGHT: 5
  ANCHOR_HEIGHTS_LIST: []
PREPARE:
  SLOP_THRESHOLD: 1
TRAIN:
  USE_FLIPPED: False
  USE_CACHED: False
  CACHE_PATH: dataset/cache
  TRAIN_PATH: dataset/for_train
  COORDINATE_NUM: 4
  IMS_BATCH_SIZE: 1  # 每轮图片的数目
  PIXEL_MEANS: [102.9801, 115.9465, 122.7717]
  MAX_SIZE: 1000
  WEIGHT_DECAY: 0.0005 #正则化项的系数
  RPN_NEGATIVE_OVERLAP: 0.3
  RPN_POSITIVE_OVERLAP: 0.7
  RPN_FG_FRACTION: 0.25
  RPN_BATCHSIZE: 300
  OHEM: False
  LEARNING_RATE: 0.0001
  SOLVER: "Momentum"
  MOMENTUM: 0.9
  STEPSIZE: 14000
  GAMMA: 0.1
  DISPLAY: 1
  MAX_ITER: 50004
  SNAPSHOT_ITERS: 10
  RANDOM_DOWNSAMPLE: Ture
  SCALE: 800
TEST:
  DETECT_MODE: "O" # 字符"O"表示检测倾斜的，字符"H"表示检测水平的
  DATA_DIR: dataset/for_test # 测试图片的存储路径
  RESULT_DIR_PIC: data/results/pic # 结果图片路径
  RESULT_DIR_TXT: data/results/gt_txt # 结果图片路径
  SCALE: 2000
  MAX_SCALE: 2600
  TEXT_PROPOSALS_WIDTH: 16
  MIN_NUM_PROPOSALS: 2 # 文本的宽度最小由几个片段构成，乘以TEXT_PROPOSALS_WIDTH，则表示最小由几个像素构成
  MIN_RATIO: 0.5 # 文本的宽度除以高度的阈值
  LINE_MIN_SCORE: 0.89 # 整个文本的分数阈值，，
  MAX_HORIZONTAL_GAP: 50  # 水平片段大于该值的，就不连接在一起了
  TEXT_PROPOSALS_MIN_SCORE: 0.85 # 对于anchor而言，大于该分数就判定为正例
  MIN_V_OVERLAPS: 0.08  # y方向IOU大于该值的，就算相邻
  MIN_SIZE_SIM: 0.6  # y方向的相似度大于该值，就判定为相邻
  RPN_PRE_NMS_TOP_N: 12000
  RPN_POST_NMS_TOP_N: 2000
  RPN_NMS_THRESH: 0.08  # 非极大值抑制的阈值，y_iou大于该阈值，就会被抑制掉
  RPN_MIN_SIZE: 16
  RATIO: 5 # 在连接的时候，以分数和y_iou共同作为评判标准，分数的系数是1，该值反映y_iou的占比
  CONNECT: False  # 要不要把所有anchor连接起来输出
  NMS_RATIO: 2.6  # 在进行非极大值抑制的时候，小文本的阈值要调高一点，大文本阈值要调低一点。用该值控制，他需要大于1
  # 当anchor高度为256时， 阈值为RPN_NMS_THRESH；当anchor高度为2时，阈值是RPN_NMS_THRESH*RATIO，线性变化
  BIG_CONNECT: False  # 如果是True，就把在同一高度的大anchor连接起来
  BIG_THRESH: 80  # 大于该值的anchor才进行高度连接
  BIG_IOU: 0.01  # 大anchor连接的iou阈值，大于该值的，就合并。该阈值必须小于RPN_NMS_THRESH


